global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.163.com:25'
  smtp_from: 'stars_jzl@163.com'
  smtp_auth_username: 'stars_jzl@163.com'
  smtp_auth_password: 'CCYRLIWOTERVIBSL'
  smtp_hello: '163.com'
  smtp_require_tls: false
route:
  group_by: ['job', 'severity']
  group_wait: 5s
  group_interval: 5m
  repeat_interval: 12h
  receiver: default

receivers:
- name: 'default'
  email_configs:
  - to: '353553339@qq.com'
    send_resolved: true
